/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package report6_7;

import java.text.DecimalFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author huyle
 */
public class Product extends javax.swing.JFrame {

    /**
     * Creates new form Product
     */
    public Product() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPayment = new javax.swing.JTextField();
        spQty = new javax.swing.JSpinner();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        cbDiscount = new javax.swing.JComboBox<>();
        txtPrice = new javax.swing.JTextField();
        print = new com.k33ptoo.components.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cash = new com.k33ptoo.components.KButton();
        addToCard = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Id");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 38, 80, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 103, 80, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Qty");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 33));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Discount");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Payment");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 80, 40));

        txtPayment.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 210, 40));

        spQty.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(spQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 210, 40));

        txtId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 210, 40));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 210, 40));

        cbDiscount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cbDiscount.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 %", "10 %", "20 %", "30 %", "40 %", "50 %" }));
        getContentPane().add(cbDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 210, 40));

        txtPrice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        getContentPane().add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 210, 40));

        print.setText("Print");
        print.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        getContentPane().add(print, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 410, 210, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Qty", "Price", "Discount", "Payment"
            }
        ));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 490, 340));

        cash.setText("Cash");
        cash.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });
        getContentPane().add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 210, -1));

        addToCard.setText("Add to card");
        addToCard.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addToCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToCardActionPerformed(evt);
            }
        });
        getContentPane().add(addToCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 210, -1));

        setSize(new java.awt.Dimension(896, 574));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        int qty      = Integer.parseInt(spQty.getValue().toString());
        double price = Double.parseDouble(txtPrice.getText());
        String dis   = cbDiscount.getSelectedItem().toString().substring(0, cbDiscount.getSelectedItem().toString().length() -2);
        int discount = Integer.parseInt(dis);
        
        double total = qty * price;
        
        double payment = total - (total * discount)/100;
        txtPayment.setText(String.valueOf(payment));
    }//GEN-LAST:event_cashActionPerformed

    private void addToCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToCardActionPerformed
        int id = Integer.parseInt(txtId.getText());
        String name = txtName.getText();
        double price = Double.parseDouble(txtPrice.getText());
        String dis   = cbDiscount.getSelectedItem().toString().substring(0, cbDiscount.getSelectedItem().toString().length() -2);
        int discount = Integer.parseInt(dis);
        double payment = Double.parseDouble(txtPayment.getText());
        
        ListProduct.list.add(new ListProduct(id, name, id, price, discount, payment));
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
        for (int i = 0; i < ListProduct.list.size(); i++) {
            Object row[] = {
                ListProduct.list.get(i).getId(),
                ListProduct.list.get(i).getName(),
                ListProduct.list.get(i).getQty(),
                ListProduct.list.get(i).getPrice(),
                ListProduct.list.get(i).getDiscount(),
                ListProduct.list.get(i).getPayment()
            };
            model.addRow(row);
            addToCard.setText("Add to card ("+(i+1)+")");
        }
    }//GEN-LAST:event_addToCardActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            double totaldollar = 0;
            double totalriel   = 0;
            for (int i = 0; i < ListProduct.list.size(); i++) {
                totaldollar += ListProduct.list.get(i).getPayment();
            }
            totalriel = totaldollar*4100;
            
            DecimalFormat df = new DecimalFormat("###########0.00");
            
            JasperReport report = JasperCompileManager.compileReport("src/report6_7/product.jrxml");
            HashMap<String,Object> map = new HashMap();
            map.put("totalriel", totalriel);
            map.put("totaldollar", totaldollar);
            JRBeanCollectionDataSource source = new JRBeanCollectionDataSource(ListProduct.list);
            JasperPrint print = JasperFillManager.fillReport(report, map, source);
            JasperViewer.viewReport(print);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton addToCard;
    private com.k33ptoo.components.KButton cash;
    private javax.swing.JComboBox<String> cbDiscount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton print;
    private javax.swing.JSpinner spQty;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtPrice;
    // End of variables declaration//GEN-END:variables
}
